bug and refactoring

diff --git a/portal b/portal
--- a/portal
+++ b/portal
@@ -1,80 +1,105 @@
 #!/usr/bin/env bash
 
-stty -echo
-tput civis
-
-trap 'stty echo; tput cnorm' EXIT
-
-temp_file=$(mktemp)
-
-printf '\e[8;38;108t\[\033[48;5;0;38;5;178m\]'
-
-clear
-
-cat << EOF
- ----------------------------------------------------  ----------------------------------------------------
-|                                                    ||                                                    |
-|                                                    ||                                                    |
-|                                                    ||                                                    |
-|                                                    ||                                                    |
-|                                                    ||                                                    |
-|                                                    ||                                                    |
-|                                                    ||                                                    |
-|                                                    ||                                                    |
-|                                                    ||                                                    |
-|                                                    ||                                                    |
-|                                                    ||                                                    |
-|                                                    ||                                                    |
-|                                                    ||                                                    |
-|                                                    ||                                                    |
-|                                                    ||                                                    |
-|                                                    ||                                                    |
-|                                                    | ----------------------------------------------------
-|                                                    |
-|                                                    |
-|                                                    |
-|                                                    |
-|                                                    |
-|                                                    |
-|                                                    |
-|                                                    |
-|                                                    |
-|                                                    |
-|                                                    |
-|                                                    |
-|                                                    |
-|                                                    |
-|                                                    |
-|                                                    |
-|                                                    |
- ----------------------------------------------------
-EOF
-
 print_cursors() {
     # since parralel processes can't share variables
     # they have to be written and read into a file
-    # cursor_status is a 
+    # cursor_status is a 2-character string, either 
     source $temp_file
     printf "\033[%s;%sH${cursor_status:0:1}" ${cursor_pos_lyrics[@]}
     printf '\033[17;'$cursor_pos_credits"H${cursor_status:1:1}"
 }
 
-cat >$temp_file << EOF
-cursor_status='_ '
-cursor_pos_lyrics=(2 3)
-cursor_pos_credits=57
-EOF
-source $temp_file # so that the terminal can warm up its I/O muscles
+print_lyrics() {
+    local new_line=true
+    local rate=88
+    local changing_rate=false
+    for line in "${@}"; do
+        if [ "$changing_rate" = true ]; then
+            rate=$line
+            changing_rate=false # so that the next argument doesn't get caught
+            continue
+        fi
 
-while true; do
-    sed -i "1s/'.*'/'${cursor_status:1:1}${cursor_status:0:1}'/" $temp_file
-    print_cursors
-    sleep .3
-done &
+        if [[ $line == -* ]]; then # if "option" , currently -c -n -r
+            case ${line:1:1} in
+                r ) # set a variable since the next argument will be the value
+                changing_rate=true
+             ;; n ) # set a variable to remember for the next line
+                new_line=false
+             ;; c ) # clear the screen
+                cursor_pos_lyrics=(2 3)
+                sed -i '2s/(.*)/(2 3)/' $temp_file
+                for i in {2..35}; do
+                    printf "\033[$i;3H%s" \
+                        '                                                 '
+                done
+             ;;
+            esac
+            continue
+        fi
+
+        if [[ $line =~ ^[0-9]+$ ]]; then
+            # if the line is a number (not proceeded by -r)
+            # then sleep until that time (in tenths of a second, i.e. 10=1s)
+            # measured from the start of animation
+            if (( start + line*10**8 > $(date +%s%N) )); then
+                # check used since sleep can't receives a negative value
+                sleep $(bc <<< "scale=3; $line/10+($start-$(date +%s%N))/10^9")
+            fi
+            continue
+        fi
+
+        # uncomment line below for line error checking
+        # local cursor_pos_start=${cursor_pos_lyrics[1]}
+
+        local lyrics_time=$(date +%s%N)
+        for (( char=0; char<${#line}; char++ )); do
+
+            # update and record new cursor position
+            (( cursor_pos_lyrics[1]++ ))
+            sed -i "2s/[0-9]*)/${cursor_pos_lyrics[1]})/" $temp_file
+
+            for _ in 1 2; do # print twice because it sometimes fails first time
+                printf "\033[${cursor_pos_lyrics[0]};%sH${line:$char:1}" \
+                    $(( ${cursor_pos_lyrics[1]}-1 ))
+            done
+
+            print_cursors # redraw the cursor on the next character
+
+            if ((  lyrics_time + rate*10**6 > $(date +%s%N) )); then
+                sleep $(bc <<< \
+                    "scale=3; $rate/10^3+($lyrics_time-$(date +%s%N))/10^9" )
+            fi
+            lyrics_time=$(date +%s%N)
+        done
+
+        # uncomment line below for line error checking
+        # record new cursor position
+        # (( cursor_pos_lyrics[1]=cursor_pos_start+${#line} ))
+        # sed -i "2s/[0-9]*)/$(( cursor_pos_start+${#line} )))/" $temp_file
+        # printf "\033[${cursor_pos_lyrics[0]};"$cursor_pos_start"H$line"
+
+        rate=88 # change rate back to default
+
+        if [ "$new_line" = true ]; then
+            last_char=${cursor_pos_lyrics[@]}
+            sed -i "2s/(.*)/($(( cursor_pos_lyrics[0]+1 )) 3)/" $temp_file
+
+            # print a space over where the cursor used to be
+            printf '\033[%s;%sH ' ${last_char[@]}
+
+            print_cursors
+        else
+            new_line=true
+        fi
+    done
+}
 
 print_ascii_art() {
-    if [ $1 ]; then
-        case $1 in
+                    # if there is an argument, then it is a string code for a
+                    # piece that is used multiple times, therefore cached here
+    if [ $1 ]; then # if there is no argument
+        case $1 in  # then there is a heredoc containing the art to be printed
             'logo' ) print_ascii_art << 'EOF'
               .,-:;//;:=,
           . :H@@@MM@M#H/.,+%;,
@@ -167,7 +192,10 @@ EOF
         esac
     else
         local line_no=19
-        local IFS=''
+        local IFS='' # so that whitespace in the heredoc is preserved
+                     # this has the side effect that the spaces printed after
+                     # the art (to cover up any previous residue)
+                     # have to be explicitly 
         while read -r line; do
             printf "\033[$(( line_no++ ));61H%s\033[49D%s" \
                 '                                                ' $line
@@ -175,89 +203,63 @@ EOF
     fi
 }
 
-print_lyrics() {
-    local new_line=true
-    local rate=88
-    local changing_rate=false
-    for line in "${@}"; do
-        if [ "$changing_rate" = true ]; then
-            rate=$line
-            changing_rate=false # so that the next argument doesn't get caught
-            continue
+stty -echo && tput civis # disable entering characters and hide the cursor
+trap 'stty echo; tput cnorm' EXIT # undo the above upon exit
 
-        if [[ $line == -* ]]; then # if "option" , currently -c -n -r
-            case ${line:1:1} in
-                r ) # set a variable since the next argument will be the value
-                changing_rate=true
-             ;; n ) # set a variable to remember for the next line
-                new_line=false
-             ;; c ) # clear the screen
-                cursor_pos_lyrics=(2 3)
-                sed -i '2s/(.*)/(2 3)/' $temp_file
-                for i in {2..35}; do
-                    printf "\033[$i;3H%s" \
-                        '                                                 '
-                done
-             ;;
-            esac
-            continue
-        fi
+temp_file=$(mktemp)
+cat >$temp_file << EOF
+cursor_status='_ '
+cursor_pos_lyrics=(2 3)
+cursor_pos_credits=57
+EOF
+source $temp_file # to avoid writing the same thing twice
 
-        if [[ $line =~ ^[0-9]+$ ]]; then
-            # if the line is a number (not proceeded by -r)
-            # then sleep until that time (in tenths of a second, i.e. 10=1s)
-            # measured from the start of animation
-            if (( start + line*10**8 > $(date +%s%N) )); then
-                # check used since sleep can't receives a negative value
-                sleep $(bc <<< "scale=3; $line/10+($start-$(date +%s%N))/10^9")
-            fi
-            continue
-        fi
+printf '\e[8;38;108t\[\033[48;5;0;38;5;178m\]'
+clear
+cat << EOF
+ ----------------------------------------------------  ----------------------------------------------------
+|                                                    ||                                                    |
+|                                                    ||                                                    |
+|                                                    ||                                                    |
+|                                                    ||                                                    |
+|                                                    ||                                                    |
+|                                                    ||                                                    |
+|                                                    ||                                                    |
+|                                                    ||                                                    |
+|                                                    ||                                                    |
+|                                                    ||                                                    |
+|                                                    ||                                                    |
+|                                                    ||                                                    |
+|                                                    ||                                                    |
+|                                                    ||                                                    |
+|                                                    ||                                                    |
+|                                                    ||                                                    |
+|                                                    | ----------------------------------------------------
+|                                                    |
+|                                                    |
+|                                                    |
+|                                                    |
+|                                                    |
+|                                                    |
+|                                                    |
+|                                                    |
+|                                                    |
+|                                                    |
+|                                                    |
+|                                                    |
+|                                                    |
+|                                                    |
+|                                                    |
+|                                                    |
+|                                                    |
+ ----------------------------------------------------
+EOF
 
-        # uncomment line below for line error checking
-        # local cursor_pos_start=${cursor_pos_lyrics[1]}
-
-        local lyrics_time=$(date +%s%N)
-        for (( char=0; char<${#line}; char++ )); do
-            (( cursor_pos_lyrics[1]++ ))
-            sed -i "2s/[0-9]*)/${cursor_pos_lyrics[1]})/" $temp_file
-
-            for _ in 1 2; do # print twice because it sometimes fails first time
-                printf "\033[${cursor_pos_lyrics[0]};%sH${line:$char:1}" \
-                    $(( ${cursor_pos_lyrics[1]}-1 ))
-            done
-
-            print_cursors # redraw the cursor on the next character
-
-            if ((  lyrics_time + rate*10**6 > $(date +%s%N) )); then
-                sleep $(bc <<< \
-                    "scale=3; $rate/10^3+($lyrics_time-$(date +%s%N))/10^9" )
-            fi
-            lyrics_time=$(date +%s%N)
-        done
-
-        # record new cursor position
-        (( cursor_pos_lyrics[1]=cursor_pos_start+${#line} ))
-        sed -i "2s/[0-9]*)/$(( cursor_pos_start+${#line} )))/" $temp_file
-
-        # uncomment line below for line error checking
-        # printf "\033[${cursor_pos_lyrics[0]};"$cursor_pos_start"H$line"
-
-        rate=88 # change rate back to default
-
-        if [ "$new_line" = true ]; then
-            last_char=${cursor_pos_lyrics[@]}
-            sed -i "2s/(.*)/($(( cursor_pos_lyrics[0]+1 )) 3)/" $temp_file
-
-            # print a space over where the cursor used to be
-            printf '\033[%s;%sH ' ${last_char[@]}
-
-            print_cursors
-        else
-            new_line=true
-        fi
-    done
-}
+while true; do
+    sed -i "1s/'.*'/'${cursor_status:1:1}${cursor_status:0:1}'/" $temp_file
+    print_cursors
+    sleep .3
+done &
 
 start=$(date +%s%N)
 print_lyrics 1 -r 80 'Form FORM-29827281-12:' -r 80 'Test Assessment Report' \
